# Generated by Django 5.0.2 on 2024-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('birthday', models.DateField()),
                ('logo_header', models.ImageField(blank=True, null=True, upload_to='images/settings/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/settings/')),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to='images/settings/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
