# Generated by Django 5.0.2 on 2024-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='birthday',
            field=models.CharField(max_length=100),
        ),
    ]
