# Generated by Django 5.0 on 2024-02-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
