# Generated by Django 5.0 on 2024-02-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_aboutme_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
